### ISSUE TITLE
great -but

### ISSUE THREAD

**Issue by leo-22-afk** [natecdr/tuttut#19]
after getting tuttut started , the OUTPUT .txt is wired. I used the given setting for guitar but did not get the output look usable like your example. Which settings could solve this?
[Krieger_Menuett_in_A-Moll.txt](https://github.com/user-attachments/files/18008537/Krieger_Menuett_in_A-Moll.txt)

THANK YOU!

**Comment by natecdr** [comment]
Try drag & dropping your txt file onto a firefox window, you should see the file open in a new tab.
Then right click anywhere on the page and you shoud see "View page source". 
I'm on linux too and it works for me on firefox!

**Comment by leo-22-afk** [comment]
Tricky!!! Now you taught me some new software-skills---hope I'll learn to play guitar as well:::::Thank you very much and have a good time furthermore
